
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon May 12 22:08:06 CEST 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 36;
  public static final int LBRACKET = 9;
  public static final int CONST = 5;
  public static final int NOTEQUAL = 38;
  public static final int REM = 25;
  public static final int GREATER = 39;
  public static final int LPAREN = 12;
  public static final int SEMI = 6;
  public static final int CONTINUE = 31;
  public static final int LESS = 41;
  public static final int MINUS = 20;
  public static final int CHARACTER = 46;
  public static final int RPAREN = 13;
  public static final int AND = 34;
  public static final int LESSEQUAL = 42;
  public static final int OR = 33;
  public static final int BOOL = 45;
  public static final int COMMA = 8;
  public static final int INC = 18;
  public static final int DIV = 24;
  public static final int PLUS = 22;
  public static final int ASSIGN = 7;
  public static final int IF = 27;
  public static final int DOT = 26;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int EQUAL = 37;
  public static final int RBRACKET = 10;
  public static final int NEW = 21;
  public static final int error = 1;
  public static final int MUL = 23;
  public static final int NUMBER = 44;
  public static final int IDENT = 43;
  public static final int BREAK = 30;
  public static final int VOID = 11;
  public static final int GREATEREQUAL = 40;
  public static final int COLON = 14;
  public static final int UNION = 35;
  public static final int LBRACE = 3;
  public static final int ELSE = 32;
  public static final int READ = 16;
  public static final int WHILE = 29;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int DEC = 19;
  public static final int PRINT = 17;
  public static final int DO = 28;
}

